const columns=[
{'0':'EntityName'},
{'1':'EntityHomePage'},
{'2':'Sub-category'},
{'3':'Broad Category'},
{'4':'Cluster (from Sub-category)'},
{'5':'Logo'},
{'6':'Description'},
{'7':'Crunchbase URL'},
{'8':'LinkedIn URL	'},
{'9':'Github URL'},
{'10':'Developer portal'},
{'11':'Open source?'},
{'12':'Year Founded'},
{'13':'Number of Founders'},
{'14':'Founder Names'},
{'15':'Headquarters (Country)'},
{'16':'Headquarters (City)'},
{'17':'Women in Management?'},
{'18':'Diverse Management?'},
{'19':'Headcount'},
{'20':'Total Products'},
{'21':'Patents Granted'},
{'22':'Known standards/specifications used'},
{'23':'Privacy Specific Features Highlighted'},
{'24':'Pricing model'},
{'25':'Pricing page'},
{'26':'Page about banking/finance'},
{'27':'Page about health	'},
{'28':'Page about sustainability'},
{'29':'Page about government'},
{'30':'Known partnerships (API industry)'},
{'31':'Logo (from Known partnerships (API industry))'},
{'32':'Known partnerships (non-API industry)'},
{'33':'Stage (Seed, A, B, C)'},
{'34':'Total Funding'},
{'35':'Last Funding Date'},
{'36':'Acquisitions (of other entities)'},
{'37':'Acquired By	IPO Date	'},
{'38':'Money Raised at IPO (in USD)	'},
{'39':'Valuation at IPO (in USD)	'},
{'40':'Created	Last Modified	'},
{'41':'Last Modified By	'},
{'42':'Please share your email for confirmation:'},
{'43':'Site Not Loading	'},
{'44':'CMO/Marketing Lead	'},
{'45':'Contact email	'},
{'46':'apidays Sponsor?'},
]